/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 107
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 74
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__pair_token1 = 1,
  anon_sym_COLON = 2,
  sym__ignored_text = 3,
  anon_sym_if = 4,
  anon_sym_DOLLAR_LBRACE_LBRACE = 5,
  anon_sym_RBRACE_RBRACE = 6,
  anon_sym_true = 7,
  anon_sym_false = 8,
  sym_null = 9,
  anon_sym_DOT = 10,
  sym__int = 11,
  anon_sym_DASH = 12,
  anon_sym_0x = 13,
  aux_sym__hex_token1 = 14,
  anon_sym_e = 15,
  anon_sym_SQUOTE = 16,
  sym_string_content = 17,
  sym_scape_sequence = 18,
  sym__format_scape = 19,
  sym__format_content = 20,
  anon_sym_LBRACE = 21,
  anon_sym_RBRACE = 22,
  sym_asterisk = 23,
  sym_identifier = 24,
  anon_sym_LBRACK = 25,
  anon_sym_RBRACK = 26,
  anon_sym_LPAREN = 27,
  anon_sym_RPAREN = 28,
  anon_sym_COMMA = 29,
  anon_sym_format = 30,
  sym_not = 31,
  sym_lt = 32,
  sym_le = 33,
  sym_gt = 34,
  sym_ge = 35,
  sym_eq = 36,
  sym_ne = 37,
  sym_and = 38,
  sym_or = 39,
  sym_source = 40,
  sym__pair = 41,
  sym__if_pair = 42,
  sym__evaluation = 43,
  sym_expression = 44,
  sym_delimited_expression = 45,
  sym_literal = 46,
  sym_boolean = 47,
  sym__dot = 48,
  sym_number = 49,
  sym__float = 50,
  sym__hex = 51,
  sym__exp = 52,
  sym_string = 53,
  sym_format_string = 54,
  sym_format_variable = 55,
  sym_format_index = 56,
  sym_property_deref = 57,
  sym_context = 58,
  sym_property = 59,
  sym_index = 60,
  sym_function_call = 61,
  sym__function = 62,
  sym_arguments = 63,
  sym__format_function = 64,
  sym__format_arguments = 65,
  sym_operator = 66,
  sym_logical_group = 67,
  aux_sym__pair_repeat1 = 68,
  aux_sym_expression_repeat1 = 69,
  aux_sym_string_repeat1 = 70,
  aux_sym_format_string_repeat1 = 71,
  aux_sym_context_repeat1 = 72,
  aux_sym_arguments_repeat1 = 73,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__pair_token1] = "_pair_token1",
  [anon_sym_COLON] = ":",
  [sym__ignored_text] = "_ignored_text",
  [anon_sym_if] = "if",
  [anon_sym_DOLLAR_LBRACE_LBRACE] = "${{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null] = "null",
  [anon_sym_DOT] = ".",
  [sym__int] = "_int",
  [anon_sym_DASH] = "-",
  [anon_sym_0x] = "0x",
  [aux_sym__hex_token1] = "_hex_token1",
  [anon_sym_e] = "e",
  [anon_sym_SQUOTE] = "'",
  [sym_string_content] = "string_content",
  [sym_scape_sequence] = "scape_sequence",
  [sym__format_scape] = "scape_sequence",
  [sym__format_content] = "string_content",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_asterisk] = "asterisk",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_format] = "identifier",
  [sym_not] = "not",
  [sym_lt] = "lt",
  [sym_le] = "le",
  [sym_gt] = "gt",
  [sym_ge] = "ge",
  [sym_eq] = "eq",
  [sym_ne] = "ne",
  [sym_and] = "and",
  [sym_or] = "or",
  [sym_source] = "source",
  [sym__pair] = "_pair",
  [sym__if_pair] = "_if_pair",
  [sym__evaluation] = "_evaluation",
  [sym_expression] = "expression",
  [sym_delimited_expression] = "delimited_expression",
  [sym_literal] = "literal",
  [sym_boolean] = "boolean",
  [sym__dot] = "_dot",
  [sym_number] = "number",
  [sym__float] = "_float",
  [sym__hex] = "_hex",
  [sym__exp] = "_exp",
  [sym_string] = "string",
  [sym_format_string] = "format_string",
  [sym_format_variable] = "format_variable",
  [sym_format_index] = "format_index",
  [sym_property_deref] = "property_deref",
  [sym_context] = "context",
  [sym_property] = "property",
  [sym_index] = "index",
  [sym_function_call] = "function_call",
  [sym__function] = "_function",
  [sym_arguments] = "arguments",
  [sym__format_function] = "_format_function",
  [sym__format_arguments] = "arguments",
  [sym_operator] = "operator",
  [sym_logical_group] = "logical_group",
  [aux_sym__pair_repeat1] = "_pair_repeat1",
  [aux_sym_expression_repeat1] = "expression_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_format_string_repeat1] = "format_string_repeat1",
  [aux_sym_context_repeat1] = "context_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__pair_token1] = aux_sym__pair_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym__ignored_text] = sym__ignored_text,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_DOLLAR_LBRACE_LBRACE] = anon_sym_DOLLAR_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null] = sym_null,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym__int] = sym__int,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_0x] = anon_sym_0x,
  [aux_sym__hex_token1] = aux_sym__hex_token1,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_scape_sequence] = sym_scape_sequence,
  [sym__format_scape] = sym_scape_sequence,
  [sym__format_content] = sym_string_content,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_asterisk] = sym_asterisk,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_format] = sym_identifier,
  [sym_not] = sym_not,
  [sym_lt] = sym_lt,
  [sym_le] = sym_le,
  [sym_gt] = sym_gt,
  [sym_ge] = sym_ge,
  [sym_eq] = sym_eq,
  [sym_ne] = sym_ne,
  [sym_and] = sym_and,
  [sym_or] = sym_or,
  [sym_source] = sym_source,
  [sym__pair] = sym__pair,
  [sym__if_pair] = sym__if_pair,
  [sym__evaluation] = sym__evaluation,
  [sym_expression] = sym_expression,
  [sym_delimited_expression] = sym_delimited_expression,
  [sym_literal] = sym_literal,
  [sym_boolean] = sym_boolean,
  [sym__dot] = sym__dot,
  [sym_number] = sym_number,
  [sym__float] = sym__float,
  [sym__hex] = sym__hex,
  [sym__exp] = sym__exp,
  [sym_string] = sym_string,
  [sym_format_string] = sym_format_string,
  [sym_format_variable] = sym_format_variable,
  [sym_format_index] = sym_format_index,
  [sym_property_deref] = sym_property_deref,
  [sym_context] = sym_context,
  [sym_property] = sym_property,
  [sym_index] = sym_index,
  [sym_function_call] = sym_function_call,
  [sym__function] = sym__function,
  [sym_arguments] = sym_arguments,
  [sym__format_function] = sym__format_function,
  [sym__format_arguments] = sym_arguments,
  [sym_operator] = sym_operator,
  [sym_logical_group] = sym_logical_group,
  [aux_sym__pair_repeat1] = aux_sym__pair_repeat1,
  [aux_sym_expression_repeat1] = aux_sym_expression_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_format_string_repeat1] = aux_sym_format_string_repeat1,
  [aux_sym_context_repeat1] = aux_sym_context_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__pair_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym__ignored_text] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym__int] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__hex_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_scape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym__format_scape] = {
    .visible = true,
    .named = true,
  },
  [sym__format_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_asterisk] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_format] = {
    .visible = true,
    .named = true,
  },
  [sym_not] = {
    .visible = true,
    .named = true,
  },
  [sym_lt] = {
    .visible = true,
    .named = true,
  },
  [sym_le] = {
    .visible = true,
    .named = true,
  },
  [sym_gt] = {
    .visible = true,
    .named = true,
  },
  [sym_ge] = {
    .visible = true,
    .named = true,
  },
  [sym_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_ne] = {
    .visible = true,
    .named = true,
  },
  [sym_and] = {
    .visible = true,
    .named = true,
  },
  [sym_or] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__pair] = {
    .visible = false,
    .named = true,
  },
  [sym__if_pair] = {
    .visible = false,
    .named = true,
  },
  [sym__evaluation] = {
    .visible = false,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_delimited_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym__dot] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym__hex] = {
    .visible = false,
    .named = true,
  },
  [sym__exp] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_format_string] = {
    .visible = true,
    .named = true,
  },
  [sym_format_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_format_index] = {
    .visible = true,
    .named = true,
  },
  [sym_property_deref] = {
    .visible = true,
    .named = true,
  },
  [sym_context] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym__function] = {
    .visible = false,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym__format_function] = {
    .visible = false,
    .named = true,
  },
  [sym__format_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logical_group] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pair_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_format_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_context_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_function = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_function] = "function",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_arguments, 0, .inherited = true},
    {field_function, 0, .inherited = true},
  [2] =
    {field_function, 0},
  [3] =
    {field_arguments, 2},
    {field_function, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 29,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 19,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 26,
  [57] = 28,
  [58] = 27,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 79,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 93,
  [100] = 100,
  [101] = 94,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '!', 99,
        '$', 31,
        '&', 4,
        '\'', 65,
        '(', 93,
        ')', 94,
        '*', 78,
        ',', 95,
        '-', 60,
        '.', 57,
        '0', 58,
        ':', 44,
        '<', 100,
        '=', 11,
        '>', 102,
        '[', 91,
        ']', 92,
        'e', 63,
        'f', 12,
        'i', 17,
        'n', 28,
        't', 24,
        '{', 75,
        '|', 32,
        '}', 77,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 1:
      if (lookahead == '\r') ADVANCE(74);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 2:
      if (lookahead == '\r') ADVANCE(69);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '!', 98,
        '$', 31,
        '\'', 64,
        '(', 93,
        ')', 94,
        '-', 60,
        '0', 58,
        'f', 14,
        'n', 29,
        't', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(106);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(65);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '{') ADVANCE(75);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(73);
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(66);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '{') ADVANCE(76);
      if (lookahead == '}') ADVANCE(34);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(78);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(105);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(104);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(82);
      if (lookahead == 'o') ADVANCE(86);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(47);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(55);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'r') ADVANCE(89);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(96);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 28:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(84);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 30:
      if (lookahead == '{') ADVANCE(49);
      END_STATE();
    case 31:
      if (lookahead == '{') ADVANCE(30);
      END_STATE();
    case 32:
      if (lookahead == '|') ADVANCE(107);
      END_STATE();
    case 33:
      if (lookahead == '}') ADVANCE(50);
      END_STATE();
    case 34:
      if (lookahead == '}') ADVANCE(71);
      END_STATE();
    case 35:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(62);
      END_STATE();
    case 36:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 37:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '!', 99,
        '$', 31,
        '&', 4,
        '\'', 64,
        '(', 93,
        ')', 94,
        '*', 78,
        ',', 95,
        '-', 60,
        '.', 57,
        '0', 58,
        ':', 44,
        '<', 100,
        '=', 11,
        '>', 102,
        '[', 91,
        ']', 92,
        'e', 63,
        'f', 12,
        'i', 17,
        'n', 28,
        't', 24,
        '{', 75,
        '|', 32,
        '}', 77,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 38:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '!', 10,
        '&', 4,
        '\'', 64,
        '(', 93,
        ')', 94,
        ',', 95,
        '.', 57,
        '<', 100,
        '=', 11,
        '>', 102,
        '[', 91,
        ']', 92,
        'i', 42,
        '|', 32,
        '}', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(38);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 39:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        '!', 10,
        '&', 4,
        ')', 94,
        ',', 95,
        '<', 100,
        '=', 11,
        '>', 102,
        ']', 92,
        'e', 63,
        '|', 32,
        '}', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(39);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      if (lookahead == '$') ADVANCE(31);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__pair_token1);
      if (lookahead == 'f') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__pair_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__ignored_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__ignored_text);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_if);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_null);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__int);
      if (lookahead == 'x') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__int);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym__hex_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_e);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(70);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(7);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'') ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '\'') ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_scape_sequence);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__format_scape);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__format_content);
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead == '{') ADVANCE(75);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__format_content);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__format_content);
      if (lookahead == '\\') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(73);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '{') ADVANCE(71);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_asterisk);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(88);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(52);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(54);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(87);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(79);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(85);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(81);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(97);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(80);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_format);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_format);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_not);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_not);
      if (lookahead == '=') ADVANCE(105);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_lt);
      if (lookahead == '=') ADVANCE(101);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_le);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_gt);
      if (lookahead == '=') ADVANCE(103);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_ge);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_eq);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_ne);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_and);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_or);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 38},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 38},
  [14] = {.lex_state = 38},
  [15] = {.lex_state = 38},
  [16] = {.lex_state = 38},
  [17] = {.lex_state = 38},
  [18] = {.lex_state = 38},
  [19] = {.lex_state = 38},
  [20] = {.lex_state = 38},
  [21] = {.lex_state = 38},
  [22] = {.lex_state = 38},
  [23] = {.lex_state = 38},
  [24] = {.lex_state = 38},
  [25] = {.lex_state = 38},
  [26] = {.lex_state = 39},
  [27] = {.lex_state = 39},
  [28] = {.lex_state = 39},
  [29] = {.lex_state = 38},
  [30] = {.lex_state = 38},
  [31] = {.lex_state = 38},
  [32] = {.lex_state = 38},
  [33] = {.lex_state = 38},
  [34] = {.lex_state = 38},
  [35] = {.lex_state = 38},
  [36] = {.lex_state = 38},
  [37] = {.lex_state = 38},
  [38] = {.lex_state = 38},
  [39] = {.lex_state = 38},
  [40] = {.lex_state = 38},
  [41] = {.lex_state = 38},
  [42] = {.lex_state = 38},
  [43] = {.lex_state = 38},
  [44] = {.lex_state = 38},
  [45] = {.lex_state = 38},
  [46] = {.lex_state = 38},
  [47] = {.lex_state = 38},
  [48] = {.lex_state = 38},
  [49] = {.lex_state = 38},
  [50] = {.lex_state = 38},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 38},
  [53] = {.lex_state = 38},
  [54] = {.lex_state = 38},
  [55] = {.lex_state = 38},
  [56] = {.lex_state = 39},
  [57] = {.lex_state = 39},
  [58] = {.lex_state = 39},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 8},
  [63] = {.lex_state = 40},
  [64] = {.lex_state = 40},
  [65] = {.lex_state = 8},
  [66] = {.lex_state = 5},
  [67] = {.lex_state = 5},
  [68] = {.lex_state = 5},
  [69] = {.lex_state = 38},
  [70] = {.lex_state = 40},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 40},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 40},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 40},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 9},
  [85] = {.lex_state = 9},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 35},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__int] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_0x] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_scape_sequence] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_asterisk] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_format] = ACTIONS(1),
    [sym_not] = ACTIONS(1),
    [sym_lt] = ACTIONS(1),
    [sym_le] = ACTIONS(1),
    [sym_gt] = ACTIONS(1),
    [sym_ge] = ACTIONS(1),
    [sym_eq] = ACTIONS(1),
    [sym_ne] = ACTIONS(1),
    [sym_and] = ACTIONS(1),
    [sym_or] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(103),
    [sym__pair] = STATE(89),
    [sym__if_pair] = STATE(89),
    [aux_sym__pair_token1] = ACTIONS(3),
    [anon_sym_if] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(7), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    STATE(58), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(96), 2,
      sym_expression,
      sym_delimited_expression,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(47), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [61] = 17,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    ACTIONS(27), 1,
      sym__int,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym__float,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    STATE(90), 1,
      sym_arguments,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(71), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [121] = 16,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    ACTIONS(27), 1,
      sym__int,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(33), 1,
      sym_not,
    STATE(27), 1,
      sym__float,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(52), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [178] = 16,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    ACTIONS(27), 1,
      sym__int,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(35), 1,
      sym_not,
    STATE(27), 1,
      sym__float,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(45), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [235] = 16,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    ACTIONS(37), 1,
      sym_not,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    STATE(58), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(43), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [292] = 16,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    ACTIONS(27), 1,
      sym__int,
    ACTIONS(29), 1,
      anon_sym_DASH,
    ACTIONS(39), 1,
      sym_not,
    STATE(27), 1,
      sym__float,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(43), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [349] = 15,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    ACTIONS(27), 1,
      sym__int,
    ACTIONS(29), 1,
      anon_sym_DASH,
    STATE(27), 1,
      sym__float,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(42), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [403] = 15,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    ACTIONS(27), 1,
      sym__int,
    ACTIONS(29), 1,
      anon_sym_DASH,
    STATE(27), 1,
      sym__float,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(54), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [457] = 15,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    ACTIONS(27), 1,
      sym__int,
    ACTIONS(29), 1,
      anon_sym_DASH,
    STATE(27), 1,
      sym__float,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(49), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [511] = 15,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(13), 1,
      sym__int,
    ACTIONS(15), 1,
      anon_sym_DASH,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    STATE(58), 1,
      sym__float,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(49), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [565] = 15,
    ACTIONS(11), 1,
      sym_null,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      anon_sym_format,
    ACTIONS(27), 1,
      sym__int,
    ACTIONS(29), 1,
      anon_sym_DASH,
    STATE(27), 1,
      sym__float,
    STATE(36), 1,
      sym__function,
    STATE(40), 1,
      sym__format_function,
    ACTIONS(9), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(39), 3,
      sym_boolean,
      sym_number,
      sym_string,
    STATE(81), 5,
      sym__evaluation,
      sym_literal,
      sym_context,
      sym_function_call,
      sym_logical_group,
  [619] = 9,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    ACTIONS(47), 1,
      anon_sym_LPAREN,
    STATE(16), 1,
      sym_index,
    STATE(84), 1,
      sym__dot,
    STATE(85), 1,
      sym_property_deref,
    ACTIONS(49), 2,
      sym_lt,
      sym_gt,
    STATE(14), 2,
      sym_property,
      aux_sym_context_repeat1,
    ACTIONS(41), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [658] = 8,
    ACTIONS(43), 1,
      anon_sym_DOT,
    ACTIONS(45), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_index,
    STATE(84), 1,
      sym__dot,
    STATE(85), 1,
      sym_property_deref,
    ACTIONS(53), 2,
      sym_lt,
      sym_gt,
    STATE(15), 2,
      sym_property,
      aux_sym_context_repeat1,
    ACTIONS(51), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [694] = 8,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    STATE(16), 1,
      sym_index,
    STATE(84), 1,
      sym__dot,
    STATE(85), 1,
      sym_property_deref,
    ACTIONS(63), 2,
      sym_lt,
      sym_gt,
    STATE(15), 2,
      sym_property,
      aux_sym_context_repeat1,
    ACTIONS(55), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [730] = 2,
    ACTIONS(67), 2,
      sym_lt,
      sym_gt,
    ACTIONS(65), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [749] = 2,
    ACTIONS(71), 2,
      sym_lt,
      sym_gt,
    ACTIONS(69), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [768] = 2,
    ACTIONS(75), 2,
      sym_lt,
      sym_gt,
    ACTIONS(73), 12,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_DOT,
      anon_sym_LBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [787] = 4,
    ACTIONS(79), 1,
      anon_sym_DOT,
    STATE(99), 1,
      sym__dot,
    ACTIONS(81), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 10,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [810] = 2,
    ACTIONS(85), 2,
      sym_lt,
      sym_gt,
    ACTIONS(83), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [828] = 2,
    ACTIONS(89), 2,
      sym_lt,
      sym_gt,
    ACTIONS(87), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [846] = 2,
    ACTIONS(81), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [864] = 2,
    ACTIONS(93), 2,
      sym_lt,
      sym_gt,
    ACTIONS(91), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [882] = 2,
    ACTIONS(97), 2,
      sym_lt,
      sym_gt,
    ACTIONS(95), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [900] = 2,
    ACTIONS(101), 2,
      sym_lt,
      sym_gt,
    ACTIONS(99), 11,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [918] = 2,
    ACTIONS(105), 2,
      sym_lt,
      sym_gt,
    ACTIONS(103), 11,
      anon_sym_RBRACE_RBRACE,
      anon_sym_e,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [936] = 3,
    ACTIONS(107), 1,
      anon_sym_e,
    ACTIONS(81), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 10,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [956] = 2,
    ACTIONS(111), 2,
      sym_lt,
      sym_gt,
    ACTIONS(109), 11,
      anon_sym_RBRACE_RBRACE,
      anon_sym_e,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [974] = 5,
    STATE(7), 1,
      sym_operator,
    STATE(29), 1,
      aux_sym_expression_repeat1,
    ACTIONS(113), 2,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
    ACTIONS(115), 2,
      sym_lt,
      sym_gt,
    ACTIONS(118), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [997] = 2,
    ACTIONS(123), 2,
      sym_lt,
      sym_gt,
    ACTIONS(121), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1014] = 2,
    ACTIONS(127), 2,
      sym_lt,
      sym_gt,
    ACTIONS(125), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1031] = 2,
    ACTIONS(131), 2,
      sym_lt,
      sym_gt,
    ACTIONS(129), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1048] = 2,
    ACTIONS(135), 2,
      sym_lt,
      sym_gt,
    ACTIONS(133), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1065] = 2,
    ACTIONS(139), 2,
      sym_lt,
      sym_gt,
    ACTIONS(137), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1082] = 2,
    ACTIONS(143), 2,
      sym_lt,
      sym_gt,
    ACTIONS(141), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1099] = 2,
    ACTIONS(147), 2,
      sym_lt,
      sym_gt,
    ACTIONS(145), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1116] = 2,
    ACTIONS(151), 2,
      sym_lt,
      sym_gt,
    ACTIONS(149), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1133] = 2,
    ACTIONS(155), 2,
      sym_lt,
      sym_gt,
    ACTIONS(153), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1150] = 2,
    ACTIONS(159), 2,
      sym_lt,
      sym_gt,
    ACTIONS(157), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1167] = 2,
    ACTIONS(147), 2,
      sym_lt,
      sym_gt,
    ACTIONS(145), 10,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1184] = 5,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_operator,
    STATE(29), 1,
      aux_sym_expression_repeat1,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1206] = 5,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_operator,
    STATE(50), 1,
      aux_sym_expression_repeat1,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1228] = 2,
    ACTIONS(167), 2,
      sym_lt,
      sym_gt,
    ACTIONS(113), 9,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1244] = 5,
    ACTIONS(113), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_operator,
    STATE(44), 1,
      aux_sym_expression_repeat1,
    ACTIONS(115), 2,
      sym_lt,
      sym_gt,
    ACTIONS(118), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1266] = 5,
    ACTIONS(169), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(55), 1,
      aux_sym_expression_repeat1,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1288] = 5,
    ACTIONS(171), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(29), 1,
      aux_sym_expression_repeat1,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1310] = 5,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_operator,
    STATE(53), 1,
      aux_sym_expression_repeat1,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1332] = 4,
    ACTIONS(175), 1,
      anon_sym_DOT,
    STATE(93), 1,
      sym__dot,
    ACTIONS(81), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1352] = 2,
    ACTIONS(179), 2,
      sym_lt,
      sym_gt,
    ACTIONS(177), 9,
      ts_builtin_sym_end,
      anon_sym_RBRACE_RBRACE,
      anon_sym_RPAREN,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1368] = 5,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_operator,
    STATE(29), 1,
      aux_sym_expression_repeat1,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1390] = 2,
    ACTIONS(185), 5,
      anon_sym_DASH,
      anon_sym_0x,
      anon_sym_SQUOTE,
      anon_sym_LPAREN,
      sym_not,
    ACTIONS(183), 6,
      anon_sym_true,
      anon_sym_false,
      sym_null,
      sym__int,
      sym_identifier,
      anon_sym_format,
  [1406] = 5,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      sym_operator,
    STATE(41), 1,
      aux_sym_expression_repeat1,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1428] = 5,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    STATE(6), 1,
      sym_operator,
    STATE(44), 1,
      aux_sym_expression_repeat1,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1450] = 5,
    ACTIONS(191), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(46), 1,
      aux_sym_expression_repeat1,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1472] = 5,
    ACTIONS(191), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(7), 1,
      sym_operator,
    STATE(29), 1,
      aux_sym_expression_repeat1,
    ACTIONS(163), 2,
      sym_lt,
      sym_gt,
    ACTIONS(165), 6,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1494] = 2,
    ACTIONS(105), 2,
      sym_lt,
      sym_gt,
    ACTIONS(103), 8,
      ts_builtin_sym_end,
      anon_sym_e,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1509] = 2,
    ACTIONS(111), 2,
      sym_lt,
      sym_gt,
    ACTIONS(109), 8,
      ts_builtin_sym_end,
      anon_sym_e,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1524] = 3,
    ACTIONS(107), 1,
      anon_sym_e,
    ACTIONS(81), 2,
      sym_lt,
      sym_gt,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      sym_le,
      sym_ge,
      sym_eq,
      sym_ne,
      sym_and,
      sym_or,
  [1541] = 7,
    ACTIONS(17), 1,
      anon_sym_0x,
    ACTIONS(19), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      sym__int,
    ACTIONS(29), 1,
      anon_sym_DASH,
    STATE(27), 1,
      sym__float,
    STATE(22), 2,
      sym__hex,
      sym__exp,
    STATE(95), 2,
      sym_number,
      sym_string,
  [1565] = 5,
    ACTIONS(193), 1,
      anon_sym_SQUOTE,
    ACTIONS(195), 1,
      sym__format_scape,
    ACTIONS(197), 1,
      sym__format_content,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    STATE(61), 2,
      sym_format_variable,
      aux_sym_format_string_repeat1,
  [1582] = 5,
    ACTIONS(199), 1,
      anon_sym_LBRACE,
    ACTIONS(201), 1,
      anon_sym_SQUOTE,
    ACTIONS(203), 1,
      sym__format_scape,
    ACTIONS(205), 1,
      sym__format_content,
    STATE(62), 2,
      sym_format_variable,
      aux_sym_format_string_repeat1,
  [1599] = 5,
    ACTIONS(207), 1,
      anon_sym_SQUOTE,
    ACTIONS(209), 1,
      sym__format_scape,
    ACTIONS(212), 1,
      sym__format_content,
    ACTIONS(215), 1,
      anon_sym_LBRACE,
    STATE(62), 2,
      sym_format_variable,
      aux_sym_format_string_repeat1,
  [1616] = 4,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
    ACTIONS(220), 1,
      sym__ignored_text,
    ACTIONS(223), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    STATE(63), 2,
      sym_delimited_expression,
      aux_sym__pair_repeat1,
  [1630] = 4,
    ACTIONS(226), 1,
      ts_builtin_sym_end,
    ACTIONS(228), 1,
      sym__ignored_text,
    ACTIONS(230), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    STATE(63), 2,
      sym_delimited_expression,
      aux_sym__pair_repeat1,
  [1644] = 2,
    ACTIONS(234), 1,
      sym__format_scape,
    ACTIONS(232), 3,
      anon_sym_SQUOTE,
      sym__format_content,
      anon_sym_LBRACE,
  [1653] = 4,
    ACTIONS(236), 1,
      anon_sym_SQUOTE,
    ACTIONS(238), 1,
      sym_string_content,
    ACTIONS(240), 1,
      sym_scape_sequence,
    STATE(67), 1,
      aux_sym_string_repeat1,
  [1666] = 4,
    ACTIONS(242), 1,
      anon_sym_SQUOTE,
    ACTIONS(244), 1,
      sym_string_content,
    ACTIONS(246), 1,
      sym_scape_sequence,
    STATE(68), 1,
      aux_sym_string_repeat1,
  [1679] = 4,
    ACTIONS(248), 1,
      anon_sym_SQUOTE,
    ACTIONS(250), 1,
      sym_string_content,
    ACTIONS(253), 1,
      sym_scape_sequence,
    STATE(68), 1,
      aux_sym_string_repeat1,
  [1692] = 4,
    ACTIONS(256), 1,
      anon_sym_SQUOTE,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      sym_format_string,
    STATE(104), 1,
      sym__format_arguments,
  [1705] = 3,
    ACTIONS(230), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(260), 1,
      sym__ignored_text,
    STATE(64), 2,
      sym_delimited_expression,
      aux_sym__pair_repeat1,
  [1716] = 3,
    ACTIONS(262), 1,
      anon_sym_RPAREN,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    STATE(74), 1,
      aux_sym_arguments_repeat1,
  [1726] = 3,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_arguments_repeat1,
  [1736] = 2,
    ACTIONS(270), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(268), 2,
      ts_builtin_sym_end,
      sym__ignored_text,
  [1744] = 3,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_arguments_repeat1,
  [1754] = 2,
    ACTIONS(276), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(274), 2,
      ts_builtin_sym_end,
      sym__ignored_text,
  [1762] = 3,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    ACTIONS(280), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      aux_sym_arguments_repeat1,
  [1772] = 2,
    ACTIONS(285), 1,
      anon_sym_DOLLAR_LBRACE_LBRACE,
    ACTIONS(283), 2,
      ts_builtin_sym_end,
      sym__ignored_text,
  [1780] = 3,
    ACTIONS(264), 1,
      anon_sym_COMMA,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(72), 1,
      aux_sym_arguments_repeat1,
  [1790] = 2,
    ACTIONS(289), 1,
      anon_sym_DOT,
    STATE(94), 1,
      sym__dot,
  [1797] = 2,
    ACTIONS(291), 1,
      sym__int,
    STATE(92), 1,
      sym_format_index,
  [1804] = 1,
    ACTIONS(278), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1809] = 1,
    ACTIONS(293), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1814] = 1,
    ACTIONS(295), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1819] = 1,
    ACTIONS(297), 2,
      sym_asterisk,
      sym_identifier,
  [1824] = 1,
    ACTIONS(299), 2,
      sym_asterisk,
      sym_identifier,
  [1829] = 2,
    ACTIONS(301), 1,
      sym__int,
    ACTIONS(303), 1,
      anon_sym_DASH,
  [1836] = 2,
    ACTIONS(305), 1,
      anon_sym_DOT,
    STATE(101), 1,
      sym__dot,
  [1843] = 1,
    ACTIONS(307), 1,
      aux_sym__hex_token1,
  [1847] = 1,
    ACTIONS(309), 1,
      ts_builtin_sym_end,
  [1851] = 1,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
  [1855] = 1,
    ACTIONS(313), 1,
      anon_sym_RBRACE,
  [1859] = 1,
    ACTIONS(315), 1,
      anon_sym_RBRACE,
  [1863] = 1,
    ACTIONS(317), 1,
      sym__int,
  [1867] = 1,
    ACTIONS(319), 1,
      sym__int,
  [1871] = 1,
    ACTIONS(321), 1,
      anon_sym_RBRACK,
  [1875] = 1,
    ACTIONS(323), 1,
      ts_builtin_sym_end,
  [1879] = 1,
    ACTIONS(325), 1,
      anon_sym_COLON,
  [1883] = 1,
    ACTIONS(327), 1,
      sym__int,
  [1887] = 1,
    ACTIONS(329), 1,
      sym__int,
  [1891] = 1,
    ACTIONS(331), 1,
      anon_sym_COLON,
  [1895] = 1,
    ACTIONS(333), 1,
      sym__int,
  [1899] = 1,
    ACTIONS(335), 1,
      sym__int,
  [1903] = 1,
    ACTIONS(337), 1,
      ts_builtin_sym_end,
  [1907] = 1,
    ACTIONS(339), 1,
      anon_sym_RPAREN,
  [1911] = 1,
    ACTIONS(341), 1,
      anon_sym_LPAREN,
  [1915] = 1,
    ACTIONS(343), 1,
      sym__int,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 61,
  [SMALL_STATE(4)] = 121,
  [SMALL_STATE(5)] = 178,
  [SMALL_STATE(6)] = 235,
  [SMALL_STATE(7)] = 292,
  [SMALL_STATE(8)] = 349,
  [SMALL_STATE(9)] = 403,
  [SMALL_STATE(10)] = 457,
  [SMALL_STATE(11)] = 511,
  [SMALL_STATE(12)] = 565,
  [SMALL_STATE(13)] = 619,
  [SMALL_STATE(14)] = 658,
  [SMALL_STATE(15)] = 694,
  [SMALL_STATE(16)] = 730,
  [SMALL_STATE(17)] = 749,
  [SMALL_STATE(18)] = 768,
  [SMALL_STATE(19)] = 787,
  [SMALL_STATE(20)] = 810,
  [SMALL_STATE(21)] = 828,
  [SMALL_STATE(22)] = 846,
  [SMALL_STATE(23)] = 864,
  [SMALL_STATE(24)] = 882,
  [SMALL_STATE(25)] = 900,
  [SMALL_STATE(26)] = 918,
  [SMALL_STATE(27)] = 936,
  [SMALL_STATE(28)] = 956,
  [SMALL_STATE(29)] = 974,
  [SMALL_STATE(30)] = 997,
  [SMALL_STATE(31)] = 1014,
  [SMALL_STATE(32)] = 1031,
  [SMALL_STATE(33)] = 1048,
  [SMALL_STATE(34)] = 1065,
  [SMALL_STATE(35)] = 1082,
  [SMALL_STATE(36)] = 1099,
  [SMALL_STATE(37)] = 1116,
  [SMALL_STATE(38)] = 1133,
  [SMALL_STATE(39)] = 1150,
  [SMALL_STATE(40)] = 1167,
  [SMALL_STATE(41)] = 1184,
  [SMALL_STATE(42)] = 1206,
  [SMALL_STATE(43)] = 1228,
  [SMALL_STATE(44)] = 1244,
  [SMALL_STATE(45)] = 1266,
  [SMALL_STATE(46)] = 1288,
  [SMALL_STATE(47)] = 1310,
  [SMALL_STATE(48)] = 1332,
  [SMALL_STATE(49)] = 1352,
  [SMALL_STATE(50)] = 1368,
  [SMALL_STATE(51)] = 1390,
  [SMALL_STATE(52)] = 1406,
  [SMALL_STATE(53)] = 1428,
  [SMALL_STATE(54)] = 1450,
  [SMALL_STATE(55)] = 1472,
  [SMALL_STATE(56)] = 1494,
  [SMALL_STATE(57)] = 1509,
  [SMALL_STATE(58)] = 1524,
  [SMALL_STATE(59)] = 1541,
  [SMALL_STATE(60)] = 1565,
  [SMALL_STATE(61)] = 1582,
  [SMALL_STATE(62)] = 1599,
  [SMALL_STATE(63)] = 1616,
  [SMALL_STATE(64)] = 1630,
  [SMALL_STATE(65)] = 1644,
  [SMALL_STATE(66)] = 1653,
  [SMALL_STATE(67)] = 1666,
  [SMALL_STATE(68)] = 1679,
  [SMALL_STATE(69)] = 1692,
  [SMALL_STATE(70)] = 1705,
  [SMALL_STATE(71)] = 1716,
  [SMALL_STATE(72)] = 1726,
  [SMALL_STATE(73)] = 1736,
  [SMALL_STATE(74)] = 1744,
  [SMALL_STATE(75)] = 1754,
  [SMALL_STATE(76)] = 1762,
  [SMALL_STATE(77)] = 1772,
  [SMALL_STATE(78)] = 1780,
  [SMALL_STATE(79)] = 1790,
  [SMALL_STATE(80)] = 1797,
  [SMALL_STATE(81)] = 1804,
  [SMALL_STATE(82)] = 1809,
  [SMALL_STATE(83)] = 1814,
  [SMALL_STATE(84)] = 1819,
  [SMALL_STATE(85)] = 1824,
  [SMALL_STATE(86)] = 1829,
  [SMALL_STATE(87)] = 1836,
  [SMALL_STATE(88)] = 1843,
  [SMALL_STATE(89)] = 1847,
  [SMALL_STATE(90)] = 1851,
  [SMALL_STATE(91)] = 1855,
  [SMALL_STATE(92)] = 1859,
  [SMALL_STATE(93)] = 1863,
  [SMALL_STATE(94)] = 1867,
  [SMALL_STATE(95)] = 1871,
  [SMALL_STATE(96)] = 1875,
  [SMALL_STATE(97)] = 1879,
  [SMALL_STATE(98)] = 1883,
  [SMALL_STATE(99)] = 1887,
  [SMALL_STATE(100)] = 1891,
  [SMALL_STATE(101)] = 1895,
  [SMALL_STATE(102)] = 1899,
  [SMALL_STATE(103)] = 1903,
  [SMALL_STATE(104)] = 1907,
  [SMALL_STATE(105)] = 1911,
  [SMALL_STATE(106)] = 1915,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 0), SHIFT_REPEAT(84),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_context_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_context_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hex, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__hex, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 3, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exp, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__exp, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__float, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 4, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__float, 4, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function, 4, 0, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__function, 4, 0, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__function, 3, 0, 2),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__function, 3, 0, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_function, 3, 0, 2),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__format_function, 3, 0, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_group, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_group, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_group, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_group, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 1, 0, 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 1, 0, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_function, 4, 0, 3),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__format_function, 4, 0, 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_logical_group, 5, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_logical_group, 5, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expression_repeat1, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expression_repeat1, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [212] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_format_string_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pair_repeat1, 2, 0, 0),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pair_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pair_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__pair, 3, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_format_variable, 3, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_variable, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [250] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [253] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_arguments, 2, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimited_expression, 3, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimited_expression, 3, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimited_expression, 5, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimited_expression, 5, 0, 0),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimited_expression, 4, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimited_expression, 4, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__format_arguments, 1, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 2, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_string, 3, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_deref, 1, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_format_index, 1, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__if_pair, 3, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [337] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gh_actions_expressions(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gh_actions_expressions",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
